apiVersion: v1
kind: ServiceAccount
metadata:
  name: py-gpu-sche
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: py-gpu-sche
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: py-gpu-sche
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: ngx-scheduler
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ngx-scheduler
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngx-scheduler
  template:
    metadata:
      labels:
        app: ngx-scheduler
    spec:
      serviceAccountName: py-gpu-sche
      containers:
      - name: py-gpu-sche
        image: us-docker.pkg.dev/jscheng-cloudrun/cr/py-gpu-sche:0.3.1
        ports:
        - containerPort: 8080
          protocol: TCP
